version: '3.7'
services:
  app:
    image: aiogram/telegram-bot-api:latest
    volumes:
      - data:/send_tg/data/

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /run/desktop/mnt/host/c/Users/User/Downloads/Telegram Desktop